### ISSUE TITLE
Is this tool supported?

### ISSUE THREAD

**Issue by jjmmolina** [corbel-platform/corbel#19]
We are studying to use this tool but we have a lot of doubts about the support because the documentation is empty and the instructions to install are insufficient (now I'm trying to install and maven shows errors)

**Comment by yebenes** [comment]
Hello Jesús,

Yes, the tool is supported. As you can see we are adding new features as we need them. The documentation is another of our pending tasks, you can see it here: https://corbel-platform.github.io/ but it is true that it is too little.

We are here for whatever you need.

Regards, Alberto.
